# Generated by Django 4.0.4 on 2023-01-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='blog_post',
        ),
    ]
